def _bullet(items: list) -> str:
    if not items:
        return "None stated."
    return "\n".join(f"- {item}" for item in items)


def _case_row(case: dict, scenario_idx: int) -> list[str]:
    preconditions = "; ".join(case.get("preconditions", [])) or "None"
    steps = "<br>".join(
        f"{i + 1}. {step}" for i, step in enumerate(case.get("steps", []))
    )
    trace = "; ".join(case.get("traceability", []))
    priority = case.get("priority", "medium").upper()
    auto = "Yes" if case.get("automation_candidate") else "No"
    return [
        case.get("case_id", f"TC-{scenario_idx:02d}.01"),
        preconditions,
        steps,
        case.get("expected_result", ""),
        case.get("test_data") or "—",
        priority,
        auto,
        trace,
    ]


def _table(headers: list[str], rows: list[list[str]]) -> str:
    header = "| " + " | ".join(headers) + " |"
    sep = "|" + "|".join("---" for _ in headers) + "|"
    body = "\n".join(
        "| " + " | ".join(str(cell).replace("|", "\\|") for cell in row) + " |"
        for row in rows
    )
    return f"{header}\n{sep}\n{body}"


def render_markdown(plan: dict) -> str:
    """Render a validated TestPlan into a professional Markdown document."""
    key = plan.get("source_jira_id", "UNKNOWN")
    lines = [
        f"# 🧪 Test Plan — {plan.get('title', key)}",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Plan ID | {plan.get('plan_id', 'TP-' + key)} |",
        f"| Source Jira Issue | {key} |",
        f"| Generated At | {plan.get('generated_at', '')} |",
        f"| Author | {plan.get('author', 'AI Test Plan Agent')} |",
        f"| Version | {plan.get('version', '1.0')} |",
        f"| Model | {plan.get('model', 'LLM')} |",
        "",
        "## 1. Scope",
        "",
        "### In Scope",
        _bullet(plan.get("scope", {}).get("in_scope", [])),
        "",
        "### Out of Scope",
        _bullet(plan.get("scope", {}).get("out_of_scope", [])),
        "",
        "### Assumptions",
        _bullet(plan.get("scope", {}).get("assumptions", [])),
        "",
        "## 2. Test Strategy",
        "",
        plan.get("test_strategy", "Not specified."),
        "",
        "## 3. Test Data",
        "",
        _bullet(plan.get("test_data", [])),
        "",
        "## 4. Environment",
        "",
        _bullet(plan.get("environment", [])),
        "",
        "## 5. Scenarios",
        "",
    ]

    headers = [
        "Case ID",
        "Preconditions",
        "Steps",
        "Expected Result",
        "Test Data",
        "Priority",
        "Automation",
        "Traceability",
    ]
    for s_idx, scenario in enumerate(plan.get("scenarios", []), start=1):
        sid = scenario.get("scenario_id", f"SC-{s_idx:02d}")
        lines.append(f"### {sid} — {scenario.get('title', 'Untitled scenario')}")
        lines.append("")
        lines.append(scenario.get("description", ""))
        lines.append("")
        lines.append(_table(headers, [_case_row(c, s_idx) for c in scenario.get("test_cases", [])]))
        lines.append("")

    lines += [
        "## 6. Traceability Matrix",
        "",
        _table(
            ["Requirement", "Test Case IDs"],
            [
                [row.get("requirement", ""), ", ".join(row.get("case_ids", []))]
                for row in plan.get("traceability_matrix", [])
            ],
        ),
        "",
        "## 7. Low-Confidence Notes",
        "",
        _bullet(plan.get("low_confidence_notes", [])),
        "",
        "---",
        "",
        "*Generated by the AI Test Plan Agent (BLAST pipeline: fetch → normalize → generate → deliver).*",
        "",
    ]
    return "\n".join(lines)
